/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : CategoryId,
  'name' : string,
  'description' : string,
  'image' : [] | [ExternalBlob],
}
export type CategoryId = string;
export type ExternalBlob = Uint8Array;
export type Gender = { 'female' : null } |
  { 'male' : null } |
  { 'unisex' : null };
export type OrderId = bigint;
export interface OrderItem {
  'size' : Size,
  'productId' : string,
  'quantity' : bigint,
  'price' : Price,
}
export interface OrderRecord {
  'id' : OrderId,
  'customerName' : string,
  'status' : OrderStatus,
  'total' : Price,
  'city' : string,
  'createdAt' : Time,
  'address' : string,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export type Price = bigint;
export interface Product {
  'id' : ProductId,
  'featured' : boolean,
  'inStock' : boolean,
  'inspiredBy' : string,
  'name' : string,
  'createdAt' : Time,
  'tags' : Array<string>,
  'description' : string,
  'sizes' : Array<SizeVariant>,
  'gender' : Gender,
  'category' : CategoryId,
  'image' : [] | [ExternalBlob],
}
export type ProductId = string;
export interface Review {
  'id' : ReviewId,
  'customerName' : string,
  'createdAt' : Time,
  'productId' : ProductId,
  'comment' : string,
  'rating' : bigint,
}
export type ReviewId = bigint;
export type Size = bigint;
export interface SizeVariant { 'size' : Size, 'price' : Price }
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReview' : ActorMethod<[ProductId, string, bigint, string], ReviewId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    CategoryId
  >,
  'createProduct' : ActorMethod<
    [
      string,
      string,
      CategoryId,
      Array<SizeVariant>,
      [] | [ExternalBlob],
      Gender,
      Array<string>,
      boolean,
      boolean,
      string,
    ],
    ProductId
  >,
  'deleteCategory' : ActorMethod<[CategoryId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getCategory' : ActorMethod<[CategoryId], Category>,
  'getOrders' : ActorMethod<[], Array<OrderRecord>>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getProductReviews' : ActorMethod<[ProductId], Array<Review>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [string, string, string, string, Array<OrderItem>, Price],
    OrderId
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCategory' : ActorMethod<
    [CategoryId, string, string, [] | [ExternalBlob]],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [
      ProductId,
      string,
      string,
      CategoryId,
      Array<SizeVariant>,
      [] | [ExternalBlob],
      Gender,
      Array<string>,
      boolean,
      boolean,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];