/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductId = IDL.Text;
export const ReviewId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CategoryId = IDL.Text;
export const Size = IDL.Nat;
export const Price = IDL.Nat;
export const SizeVariant = IDL.Record({ 'size' : Size, 'price' : Price });
export const Gender = IDL.Variant({
  'female' : IDL.Null,
  'male' : IDL.Null,
  'unisex' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const Category = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderItem = IDL.Record({
  'size' : Size,
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : Price,
});
export const OrderRecord = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'total' : Price,
  'city' : IDL.Text,
  'createdAt' : Time,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const Product = IDL.Record({
  'id' : ProductId,
  'featured' : IDL.Bool,
  'inStock' : IDL.Bool,
  'inspiredBy' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'sizes' : IDL.Vec(SizeVariant),
  'gender' : Gender,
  'category' : CategoryId,
  'image' : IDL.Opt(ExternalBlob),
});
export const Review = IDL.Record({
  'id' : ReviewId,
  'customerName' : IDL.Text,
  'createdAt' : Time,
  'productId' : ProductId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReview' : IDL.Func(
      [ProductId, IDL.Text, IDL.Nat, IDL.Text],
      [ReviewId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [CategoryId],
      [],
    ),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        CategoryId,
        IDL.Vec(SizeVariant),
        IDL.Opt(ExternalBlob),
        Gender,
        IDL.Vec(IDL.Text),
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
      ],
      [ProductId],
      [],
    ),
  'deleteCategory' : IDL.Func([CategoryId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCategory' : IDL.Func([CategoryId], [Category], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getProductReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem), Price],
      [OrderId],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCategory' : IDL.Func(
      [CategoryId, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        IDL.Text,
        CategoryId,
        IDL.Vec(SizeVariant),
        IDL.Opt(ExternalBlob),
        Gender,
        IDL.Vec(IDL.Text),
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductId = IDL.Text;
  const ReviewId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CategoryId = IDL.Text;
  const Size = IDL.Nat;
  const Price = IDL.Nat;
  const SizeVariant = IDL.Record({ 'size' : Size, 'price' : Price });
  const Gender = IDL.Variant({
    'female' : IDL.Null,
    'male' : IDL.Null,
    'unisex' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const Category = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderItem = IDL.Record({
    'size' : Size,
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : Price,
  });
  const OrderRecord = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'total' : Price,
    'city' : IDL.Text,
    'createdAt' : Time,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'featured' : IDL.Bool,
    'inStock' : IDL.Bool,
    'inspiredBy' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'sizes' : IDL.Vec(SizeVariant),
    'gender' : Gender,
    'category' : CategoryId,
    'image' : IDL.Opt(ExternalBlob),
  });
  const Review = IDL.Record({
    'id' : ReviewId,
    'customerName' : IDL.Text,
    'createdAt' : Time,
    'productId' : ProductId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReview' : IDL.Func(
        [ProductId, IDL.Text, IDL.Nat, IDL.Text],
        [ReviewId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [CategoryId],
        [],
      ),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          CategoryId,
          IDL.Vec(SizeVariant),
          IDL.Opt(ExternalBlob),
          Gender,
          IDL.Vec(IDL.Text),
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
        ],
        [ProductId],
        [],
      ),
    'deleteCategory' : IDL.Func([CategoryId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCategory' : IDL.Func([CategoryId], [Category], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getProductReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem), Price],
        [OrderId],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCategory' : IDL.Func(
        [CategoryId, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Text,
          CategoryId,
          IDL.Vec(SizeVariant),
          IDL.Opt(ExternalBlob),
          Gender,
          IDL.Vec(IDL.Text),
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };